name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    - name: Running tests
      run: |
        pytest --cache-clear --junitxml ./test-report.xml --cov-report term-missing:skip-covered --cov fild_ui > pytest-coverage.txt

    - name: Pytest coverage comment
      if: always()
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./test-report.xml

    - name: Publish test report
      if: always()
      uses: elenakulgavaya/pytest-report-action@v1.3
      with:
        path: test-report.xml
